name: Build Electron Dist

on:
  push:
    branches: [ "master", "kpmy-action-build-distro" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: electronuserland/builder:wine
      options: --user root
    steps:
    - uses: actions/checkout@v3 
    - run: npm install --legacy-peer-deps 
    - run: cd app
    - run: npm install --legacy-peer-deps --target_arch=x64 --target_platform=win32
    - run: cd ..
    - run: npm run build:prod
    - run: apt-get -qq update && apt-get install -y sudo
    - run: sudo adduser --gecos "" github
    - run: pwd
    - run: sudo chown -R github $(pwd)
    - run: sudo -u github npm run electron:build  
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: release/didveli-gallery 1.0.0.exe
        asset_name: didveli.installer.exe
        tag: ${{ github.ref }}
        overwrite: true
